@echo off
echo Iniciando o Dashboard do Sistema de Irrigacao Inteligente...
echo.
echo Instalando dependencias necessarias...
pip install streamlit pandas numpy matplotlib plotly
echo.
echo Criando o banco de dados...
python src/initialize_database.py
echo.
echo Iniciando o dashboard...
streamlit run src/dashboard.py
pause